name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ENV_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          ENV_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          ENV_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          ENV_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          ENV_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          ENV_PASSWORD_SALT_ROUNDS: ${{ secrets.PASSWORD_SALT_ROUNDS }}
          ENV_REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION }}
          ENV_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

      - run: npm i
      - run: npx jest
      - run: npm run test-teardown
