name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: 'Create env file'
        run: |
          touch .env.test
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          echo DATABASE_HOST: ${{ secrets.DATABASE_HOST }} >> .env
          echo DATABASE_NAME: ${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_PORT: ${{ secrets.DATABASE_PORT }} >> .env
          echo DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }} >> .env
          echo PASSWORD_SALT_ROUNDS: ${{ secrets.PASSWORD_SALT_ROUNDS }} >> .env
          echo REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION }} >> .env
          echo REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }} >> .env
          cat .env

      - run: npm i
      - run: npx jest
      - run: npm run test-teardown
